def fetch_industry_data(cur):
    cur.execute("SELECT primary_key, industries FROM crunchbase")
    raw_industry_data = cur.fetchall()
    return raw_industry_data

def simplify_industry_data(raw_industry_data):
    """Converts raw crucnhbase industry strings into more useful industry categories"""
    simplified_industry_data = []

    for item in raw_industry_data:
        primary_key, raw_industries = item
        industries = raw_industries.split(',')
        temp_industry_data=set()
        for industry in industries:
            industry=industry.strip()
            simplified_industry = industry_simplification_mapping.get(industry,None)
            if simplified_industry:
                industry = simplified_industry
            temp_industry_data.add(industry)
    
        industry_list=list(temp_industry_data)
        for industry in industry_list:
            simplified_industry_data.append((primary_key, industry))


    return simplified_industry_data

def insert_industry_data(cur, simplified_industry_data):
    for item in simplified_industry_data:
        crunchbase_primary_key, industry = item
        cur.execute(
            "INSERT INTO industry_connections (crunchbase_primary_key, industry_name) VALUES (%s, %s)",
            (crunchbase_primary_key, industry)
        )

"""Simplifies raw crunchbase industry data into a more useful form"""
industry_simplification_mapping={
    'Email Marketing': 'Marketing',
    'Cause Marketing': 'Marketing',
    'Podcast': 'Media and Entertainment',
    'Financial Exchanges': 'Financial Services',
    'Legal': 'Legal Tech',
    'Therapeutics': 'Health Care',
    'Biometrics': 'Security',
    'Developer APIs': 'Developer Tools',
    '3D Technology': 'Technology',
    'Sports Leagues and Teams': 'Sports',
    'Telehealth': 'Health Care',
    'Scheduling': 'Productivity Tools',
    'Forestry': 'Natural Resources',
    'Data Storage': 'Data Management',
    'Aquaculture': 'Agriculture',
    'Building Material': 'Construction',
    'Data Integration': 'Data Management',
    'Broadcasting': 'Media and Entertainment',
    'Food and Beverage': 'Consumer Goods',
    'Health Diagnostics': 'Health Care',
    'Lending': 'Financial Services',
    'Online Auctions': 'E-Commerce',
    'Shopping': 'Retail',
    'TV Production': 'Media and Entertainment',
    'College Recruiting': 'Recruiting',
    'Database': 'Data Management',
    'Food Processing': 'Food and Beverage',
    'Property Insurance': 'Insurance',
    'Pharmaceutical': 'Health Care',
    'Quality Assurance': 'Software Engineering',
    'Diabetes': 'Health Care',
    'Ad Retargeting': 'Marketing',
    'Dental': 'Health Care',
    'Sales Enablement': 'Sales',
    'Information Services': 'Information Technology',
    'Property Management': 'Real Estate',
    'Enterprise Applications': 'Enterprise Software',
    'Publishing': 'Media and Entertainment',
    'Jewelry': 'Retail',
    'Impact Investing': 'Financial Services',
    'Personal Development': 'Education',
    'Packaging Services': 'Manufacturing',
    'Accounting': 'Financial Services',
    'Nuclear': 'Energy',
    'Virtualization': 'Cloud Computing',
    'Adventure Travel': 'Travel',
    'Navigation': 'Location Based Services',
    'Military': 'National Security',
    'Cloud Management': 'Cloud Computing',
    'Data Management': 'Data Management',
    'Software Engineering': 'Software',
    'Web Development': 'Web Design',
    'Content Discovery': 'Digital Media',
    'Browser Extensions': 'Software',
    'Video Editing': 'Media and Entertainment',
    'Organic': 'Food and Beverage',
    'Venture Capital': 'Financial Services',
    'Insurance': 'Insurance',
    'Information and Communications Technology (ICT)': 'Information Technology',
    'Food Delivery': 'Delivery Service',
    'Sharing Economy': 'Marketplace',
    'Consumer Software': 'Software',
    'Bitcoin': 'Cryptocurrency',
    'Child Care': 'Family',
    'Intelligent Systems': 'Artificial Intelligence (AI)',
    'Information Technology': 'Information Technology',
    'Retail Technology': 'Retail',
    'Messaging': 'Communications Infrastructure',
    'Leasing': 'Real Estate',
    'Architecture': 'Construction',
    'Charging Infrastructure': 'Energy',
    'Energy Management': 'Energy',
    'Film': 'Media and Entertainment',
    'Lighting': 'Energy',
    'A/B Testing': 'Marketing Automation',
    'Autonomous Vehicles': 'Automotive',
    'Machinery Manufacturing': 'Manufacturing',
    'Natural Language Processing': 'Artificial Intelligence (AI)',
    'Consumer Electronics': 'Electronics',
    'Mental Health': 'Health Care',
    'Ventilation': 'Construction',
    'eSports': 'Gaming',
    'Crowdfunding': 'Funding Platform',
    'Outpatient Care': 'Health Care',
    'Product Design': 'Design',
    'Real Estate Brokerage': 'Real Estate',
    'Developer Tools': 'Software Engineering',
    'Social News': 'Media and Entertainment',
    'Parking': 'Transportation',
    'Language Learning': 'Education',
    'Fashion': 'Retail',
    'Online Games': 'Gaming',
    'Leisure': 'Recreation',
    'Vocational Education': 'Education',
    'Gift Registry': 'Retail',
    'Biotechnology': 'Life Science',
    'mHealth': 'Health Care',
    'Serious Games': 'Gaming',
    'Fleet Management': 'Logistics',
    'Consumer Applications': 'Software',
    'Simulation': 'Gaming',
    'Corporate Training': 'Education',
    'Farming': 'Agriculture',
    'EBooks': 'Digital Media',
    'Social Network': 'Social Media',
    'Wearables': 'Electronics',
    'Energy Storage': 'Energy',
    'Video Advertising': 'Marketing',
    'Higher Education': 'Education',
    'Home and Garden': 'Home Improvement',
    'Advanced Materials': 'Manufacturing',
    'Home Renovation': 'Home Improvement',
    'Consulting': 'Professional Services',
    'Audio': 'Media and Entertainment',
    'Media and Entertainment': 'Media and Entertainment',
    'Environmental Engineering': 'GreenTech',
    'Audiobooks': 'Digital Media',
    'Power Grid': 'Energy',
    'Local Business': 'Small and Medium Businesses',
    'Interior Design': 'Design',
    'Rental Property': 'Real Estate',
    'Soccer': 'Sports',
    'Social Media': 'Social Media',
    'Beauty': 'Retail',
    'Loyalty Programs': 'Marketing',
    'GovTech': 'Government',
    'Family': 'Family',
    'Primary Education': 'Education',
    'iOS': 'Mobile Apps',
    'Console Games': 'Gaming',
    'Cannabis': 'Retail',
    'Retail': 'Retail',
    'Data Visualization': 'Analytics',
    'Hardware': 'Electronics',
    'Water Purification': 'Environmental Engineering',
    'Health Insurance': 'Insurance',
    'Asset Management': 'Financial Services',
    'Waste Management': 'Environmental Consulting',
    'Delivery': 'Delivery Service',
    'Freight Service': 'Logistics',
    'Car Sharing': 'Transportation',
    'Office Administration': 'Professional Services',
    'Photography': 'Media and Entertainment',
    'DevOps': 'Software Engineering',
    'Consumer Research': 'Market Research',
    'Gift': 'Retail',
    'Marketing': 'Marketing',
    'Real Time': 'Analytics',
    'Chemical Engineering': 'Chemical',
    'EdTech': 'Education',
    'Human Computer Interaction': 'Artificial Intelligence (AI)',
    'Electronic Design Automation (EDA)': 'Electronics',
    'Communications Infrastructure': 'Information Technology',
    'Robotic Process Automation (RPA)': 'Automation',
    'IT Infrastructure': 'Information Technology',
    'Digital Entertainment': 'Media and Entertainment',
    'Travel': 'Travel',
    'Social Impact': 'Non Profit',
    'Compliance': 'Legal Tech',
    'Personal Health': 'Health Care',
    'Ports and Harbors': 'Transportation',
    'Mechanical Design': 'Mechanical Engineering',
    'Chemical': 'Chemical Engineering',
    'Facilities Support Services': 'Facility Management',
    'Decentralized Finance (DeFi)': 'Cryptocurrency',
    'Employee Benefits': 'Human Resources',
    'Cosmetic Surgery': 'Health Care',
    'Animal Feed': 'Agriculture',
    'Health Care': 'Health Care',
    'Hunting': 'Outdoors',
    'Clean Energy': 'GreenTech',
    'Commercial Lending': 'Financial Services',
    'Augmented Reality': 'Virtual Reality',
    'Delivery Service': 'Delivery Service',
    'Biopharma': 'Life Science',
    'Real Estate': 'Real Estate',
    'Marine Technology': 'Marine Transportation',
    'Usability Testing': 'Software Engineering',
    'Mining': 'Natural Resources',
    "Women's": 'Retail',
    'Heating': 'Construction',
    'Wholesale': 'Retail',
    'Social CRM': 'Customer Relationship Management (CRM)',
    'Bioinformatics': 'Life Science',
    'Civil Engineering': 'Construction',
    'PaaS': 'Cloud Computing',
    'Developer Platform': 'Developer Tools',
    'GreenTech': 'Environmental Engineering',
    'Laser': 'Technology',
    'Agriculture': 'Agriculture',
    'Web Apps': 'Software',
    'Primary and Urgent Care': 'Health Care',
    'Cloud Infrastructure': 'Cloud Computing',
    'Debt Collections': 'Financial Services',
    'Security': 'Security',
    'Sporting Goods': 'Sports',
    'Casual Games': 'Gaming',
    'B2B': 'Business Services',
    'Application Specific Integrated Circuit (ASIC)': 'Electronics',
    'Virtual Workforce': 'Professional Services',
    'Task Management': 'Productivity Tools',
    'Sustainability': 'GreenTech',
    'Penetration Testing': 'Cyber Security',
    'Public Transportation': 'Transportation',
    'Retirement': 'Financial Services',
    'Big Data': 'Data Management',
    'Sensor': 'Electronics',
    'Smart Contracts': 'Cryptocurrency',
    'Coffee': 'Food and Beverage',
    'ISP': 'Information and Communications Technology (ICT)',
    'Virtual World': 'Gaming',
    'Semiconductor': 'Electronics',
    'Natural Resources': 'Natural Resources',
    'Outdoors': 'Recreation',
    'Lead Generation': 'Marketing',
    'Mobile': 'Mobile Apps',
    'Consumer Lending': 'Financial Services',
    'STEM Education': 'Education',
    'Industrial Automation': 'Automation',
    'Service Industry': 'Professional Services',
    'Solar': 'GreenTech',
    'Mobile Payments': 'Financial Services',
    'Analytics': 'Analytics',
    'Sales Automation': 'Sales',
    'Wedding': 'Events',
    'Recreation': 'Recreation',
    'Charity': 'Non Profit',
    'Artificial Intelligence (AI)': 'Artificial Intelligence (AI)',
    'Cloud Data Services': 'Cloud Computing',
    'DSP': 'Electronics',
    'Rental': 'Real Estate',
    'Payments': 'Financial Services',
    'Predictive Analytics': 'Analytics',
    'MMO Games': 'Gaming',
    'Location Based Services': 'Location Based Services',
    'Computer': 'Electronics',
    'Risk Management': 'Financial Services',
    'Productivity Tools': 'Productivity Tools',
    'Home Decor': 'Home Improvement',
    'Cyber Security': 'Cyber Security',
    'Property Development': 'Real Estate',
    'Craft Beer': 'Food and Beverage',
    'Emerging Markets': 'Financial Services',
    'AgTech': 'Agriculture',
    'Robotics': 'Automation',
    'and Air Conditioning (HVAC)': 'Construction',
    'Event Management': 'Events',
    'Employment': 'Human Resources',
    'Affiliate Marketing': 'Marketing',
    'Restaurants': 'Food and Beverage',
    'Home Health Care': 'Health Care',
    'Personal Finance': 'Finance',
    'Sports': 'Sports',
    'IT Management': 'Information Technology',
    'Video Conferencing': 'Communications Infrastructure',
    'Genetics': 'Life Science',
    'Metaverse': 'Virtual Reality',
    'Film Production': 'Media and Entertainment',
    'CleanTech': 'GreenTech',
    'Environmental Consulting': 'GreenTech',
    'Carbon Capture': 'GreenTech',
    'Funding Platform': 'Financial Services',
    'SEO': 'Marketing',
    'Public Safety': 'Security',
    'Document Management': 'Information Technology',
    'Local': 'Local Business',
    'Children': 'Family',
    'Shoes': 'Retail',
    'Procurement': 'Supply Chain Management',
    'Satellite Communication': 'Communications Infrastructure',
    'Landscaping': 'Home Improvement',
    'Open Source': 'Software',
    'Energy': 'Energy',
    'Oil and Gas': 'Energy',
    'B2C': 'Consumer',
    'Enterprise Resource Planning (ERP)': 'Enterprise Software',
    'Smart Cities': 'Smart Home',
    'SaaS': 'Software',
    'Commercial Real Estate': 'Real Estate',
    'Dietary Supplements': 'Health Care',
    'Printing': 'Manufacturing',
    'Credit Cards': 'Financial Services',
    'Geospatial': 'Location Based Services',
    'Virtual Reality': 'Virtual Reality',
    'Digital Media': 'Digital Media',
    'Commercial Insurance': 'Insurance',
    'Embedded Software': 'Software',
    'Chatbot': 'Artificial Intelligence (AI)',
    'Building Maintenance': 'Facility Management',
    'Construction': 'Construction',
    'FinTech': 'Financial Services',
    'Data Collection and Labeling': 'Data Management',
    'E-Commerce': 'E-Commerce',
    'Human Resources': 'Human Resources',
    'Outsourcing': 'Professional Services',
    'Life Insurance': 'Insurance',
    'Business Intelligence': 'Analytics',
    'Vacation Rental': 'Travel',
    'Machine Learning': 'Artificial Intelligence (AI)',
    'Search Engine': 'Digital Media',
    'Web3': 'Blockchain',
    'Industrial': 'Manufacturing',
    'Point of Sale': 'Retail',
    'Fitness': 'Health Care',
    'Video Games': 'Gaming',
    'Small and Medium Businesses': 'Business Services',
    'Electric Vehicle': 'Automotive',
    'Music': 'Media and Entertainment',
    'Wine And Spirits': 'Food and Beverage',
    'Professional Services': 'Professional Services',
    'Drones': 'Technology',
    'Online Portals': 'Media and Entertainment',
    'Market Research': 'Market Research',
    'Nutrition': 'Health Care',
    'Advertising': 'Marketing',
    'Ad Server': 'Marketing',
    'Translation Service': 'Professional Services',
    'Video': 'Media and Entertainment',
    'Books': 'Media and Entertainment',
    'Parenting': 'Family',
    'Electronic Health Record (EHR)': 'Health Care',
    'Network Security': 'Cyber Security',
    'Mapping Services': 'Location Based Services',
    'Shipping': 'Logistics',
    'Gamification': 'Gaming',
    'Apps': 'Software',
    'Blockchain': 'Blockchain',
    'Mobile Apps': 'Mobile Apps',
    'CRM': 'Customer Relationship Management (CRM)',
    'Travel Accommodations': 'Travel',
    'Marine Transportation': 'Marine Transportation',
    'Animation': 'Media and Entertainment',
    'Computer Vision': 'Artificial Intelligence (AI)',
    'Auto Insurance': 'Insurance',
    'Social Media Management': 'Social Media',
    'SEM': 'Marketing',
    'Business Development': 'Business Services',
    'PC Games': 'Gaming',
    'Art': 'Design',
    'Angel Investment': 'Financial Services',
    'Home Services': 'Home Improvement',
    'Supply Chain Management': 'Supply Chain Management',
    'Cryptocurrency': 'Cryptocurrency',
    'SMS': 'Communications Infrastructure',
    'Video Streaming': 'Media and Entertainment',
    'Horticulture': 'Agriculture',
    'Trade Shows': 'Events',
    'Privacy': 'Cyber Security',
    'Universities': 'Higher Education',
    'Aerospace': 'Aerospace',
    'Career Planning': 'Education',
    'Internet Radio': 'Media and Entertainment',
    'Wealth Management': 'Financial Services',
    'Battery': 'Energy',
    'Digital Signage': 'Marketing',
    'Cloud Computing': 'Cloud Computing',
    'Advertising Platforms': 'Marketing',
    'Vertical Search': 'Digital Media',
    'Web Hosting': 'Information Technology',
    'Communication Hardware': 'Electronics',
    'Legal Tech': 'Legal Tech',
    'Tourism': 'Travel',
    'Smart Home': 'Smart Home',
    'Direct Sales': 'Sales',
    'Creative Agency': 'Marketing',
    'Social Media Marketing': 'Marketing',
    'UX Design': 'Design',
    'Mortgage': 'Real Estate',
    'Transportation': 'Transportation',
    'Collaboration': 'Productivity Tools',
    'Tax Preparation': 'Finance',
    'Generative AI': 'Artificial Intelligence (AI)',
    'Cosmetics': 'Retail',
    'Product Research': 'Market Research',
    'Innovation Management': 'Business Services',
    'Transaction Processing': 'Finance',
    'Events': 'Events',
    'Politics': 'Government',
    'Recruiting': 'Human Resources',
    'Web Browsers': 'Software',
    'Life Science': 'Life Science',
    'Facility Management': 'Facility Management',
    'Android': 'Mobile Apps',
    'Social': 'Social Media',
    'Web Design': 'Web Design',
    'Data Mining': 'Analytics',
    'Meeting Software': 'Productivity Tools',
    'Ride Sharing': 'Transportation',
    'Homeless Shelter': 'Non Profit',
    'Direct Marketing': 'Marketing',
    'Communities': 'Social Media',
    'Public Relations': 'Marketing',
    'Brand Marketing': 'Marketing',
    'Electrical Distribution': 'Energy',
    'Outdoor Advertising': 'Marketing',
    'Warehousing': 'Logistics',
    'Virtual Assistant': 'Artificial Intelligence (AI)',
    'Software': 'Software',
    'Electronics': 'Electronics',
    'Winery': 'Food and Beverage',
    'Association': 'Non Profit',
    'Dating': 'Social Media',
    'Psychology': 'Health Care',
    'Content Marketing': 'Marketing',
    'Hedge Funds': 'Financial Services',
    'PropTech': 'Real Estate',
    'Management Information Systems': 'Information Technology',
    'Commercial': 'Business Services',
    'Project Management': 'Productivity Tools',
    '3D Printing': 'Manufacturing',
    'Home Appliances': 'Home Improvement',
    'Quantum Computing': 'Technology',
    'Travel Agency': 'Travel',
    'Music Label': 'Media and Entertainment',
    'Elder Care': 'Health Care',
    'Water': 'Natural Resources',
    'Last Mile Transportation': 'Logistics',
    'Mobile Advertising': 'Marketing',
    'Home Improvement': 'Home Improvement',
    'Hospitality': 'Travel',
    'Advice': 'Consulting',
    'Social Recruiting': 'Human Resources',
    'Real Estate Investment': 'Real Estate',
    'Space Travel': 'Aerospace',
    'Automotive': 'Automotive',
    'Snack Food': 'Food and Beverage',
    'Customer Service': 'Customer Relationship Management (CRM)',
    'Hospital': 'Health Care',
    'Hydroponics': 'Agriculture',
    'Wireless': 'Communications Infrastructure',
    'Internet': 'Information Technology',
    'Subscription Service': 'E-Commerce',
    'Nanotechnology': 'Technology',
    'Lead Management': 'Marketing',
    'Government': 'Government',
    'Manufacturing': 'Manufacturing',
    'Music Venues': 'Media and Entertainment',
    'Janitorial Service': 'Facility Management',
    'Fraud Detection': 'Cyber Security',
    'Ticketing': 'Events',
    'Presentations': 'Productivity Tools',
    'Brewing': 'Food and Beverage',
    'Rehabilitation': 'Health Care',
    'Energy Efficiency': 'GreenTech',
    'Personalization': 'Marketing',
    'Wellness': 'Health Care',
    'Digital Marketing': 'Marketing',
    'Product Management': 'Productivity Tools',
    'Graphic Design': 'Design',
    'Medical Device': 'Health Care',
    'National Security': 'National Security',
    'Renewable Energy': 'GreenTech',
    'Skill Assessment': 'Education',
    'Identity Management': 'Security',
    'Credit': 'Financial Services',
    'Gaming': 'Gaming',
    'Reservations': 'Travel',
    'Consumer Goods': 'Consumer Goods',
    'Billing': 'Financial Services',
    'Nursing and Residential Care': 'Health Care',
    'E-Learning': 'Education',
    'Addiction Treatment': 'Health Care',
    'Mechanical Engineering': 'Mechanical Engineering',
    'Lifestyle': 'Lifestyle',
    'Bookkeeping and Payroll': 'Finance',
    'Journalism': 'Media and Entertainment',
    'Audio Recording and Production': 'Media and Entertainment',
    'Social Shopping': 'Social Media',
    'Social Entrepreneurship': 'Non Profit',
    'Secondary Education': 'Education',
    'Recycling': 'Environmental Consulting',
    'Staffing Agency': 'Human Resources',
    'Email': 'Marketing',
    'Banking': 'Financial Services',
    'Edutainment': 'Education',
    'Intellectual Property': 'Legal Tech',
    'Professional Networking': 'Professional Services',
    'Technical Support': 'Information Technology',
    'Personal Branding': 'Marketing',
    'Telecommunications': 'Communications Infrastructure',
    'Enterprise Software': 'Enterprise Software',
    'Infrastructure': 'Information Technology',
    'InsurTech': 'Insurance',
    'Gambling': 'Gaming',
    'Social Assistance': 'Non Profit',
    'Green Building': 'GreenTech',
    'Content Creators': 'Media and Entertainment',
    'Quantified Self': 'Wellness',
    'Training': 'Education',
    'Medical': 'Health Care',
    'News': 'Media and Entertainment',
    'E-Commerce Platforms': 'E-Commerce',
    'Cloud Security': 'Cyber Security',
    'Residential': 'Real Estate',
    'Event Promotion': 'Events',
    'Video Chat': 'Communications Infrastructure',
    'Trading Platform': 'Financial Services',
    'Unified Communications': 'Communications Infrastructure',
    'Management Consulting': 'Consulting',
    'Concerts': 'Events',
    'Financial Services': 'Financial Services',
    'Non Profit': 'Non Profit',
    'Alternative Medicine': 'Health Care',
    'Apparel': 'Retail',
    'Furniture': 'Home Improvement',
    'Marketplace': 'E-Commerce',
    'Finance': 'Financial Services',
    'Logistics': 'Logistics',
    'Marketing Automation': 'Marketing',
    'Sales': 'Sales',
    'Freelance': 'Professional Services',
    'Internet of Things': 'Technology',
    'Coworking': 'Real Estate',
    'Pet': 'Consumer Goods',
    'Fantasy Sports': 'Gaming',
    'Auctions': 'E-Commerce',
    'Education': 'Education',
    'Data Center': 'Information Technology',
    'Assistive Technology': 'Health Care',
    'Consumer': 'Consumer Goods',
    'Non-Fungible Token (NFT)': 'Blockchain',
    'Content': 'Digital Media'
}
